version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
  app:
    container_name: app
    image: quiz-app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/quiz"
    ports:
      - 3000:3000
